Postgres:
    environment:
        POSTGRES_DB: ${db_name}
        POSTGRES_USER: ${db_username}
        POSTGRES_PASSWORD: ${db_password}
    labels:
        io.rancher.container.pull_image: always
    tty: true
    image: postgres
    volumes:
    - ${db_data_location}:/var/lib/mysql
    stdin_open: true
    volume_driver: ${volume_driver}
